//#line 2 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the hanse_gamepad package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __hanse_gamepad__NODECONFIG_H__
#define __hanse_gamepad__NODECONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/config_init_mutex.h>

namespace hanse_gamepad
{
  class NodeConfigStatics;
  
  class NodeConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(NodeConfig &config, const NodeConfig &max, const NodeConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const NodeConfig &config1, const NodeConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, NodeConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const NodeConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, NodeConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const NodeConfig &config) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T NodeConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (NodeConfig::* field);

      virtual void clamp(NodeConfig &config, const NodeConfig &max, const NodeConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const NodeConfig &config1, const NodeConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, NodeConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const NodeConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, NodeConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const NodeConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }
    };

//#line 14 "../cfg/NodeParams.cfg"
      std::string server_hosts;
//#line 15 "../cfg/NodeParams.cfg"
      int server_port;
//#line 16 "../cfg/NodeParams.cfg"
      int frequency;
//#line 17 "../cfg/NodeParams.cfg"
      double joy_gate;
//#line 18 "../cfg/NodeParams.cfg"
      double scale_linear;
//#line 19 "../cfg/NodeParams.cfg"
      double scale_angular;
//#line 20 "../cfg/NodeParams.cfg"
      double scale_depth;
//#line 21 "../cfg/NodeParams.cfg"
      int axis_linear;
//#line 22 "../cfg/NodeParams.cfg"
      int axis_angular;
//#line 23 "../cfg/NodeParams.cfg"
      int axis_depth;
//#line 24 "../cfg/NodeParams.cfg"
      bool use_throttle;
//#line 25 "../cfg/NodeParams.cfg"
      int depth_delta;
//#line 26 "../cfg/NodeParams.cfg"
      int button_down;
//#line 27 "../cfg/NodeParams.cfg"
      int button_up;
//#line 28 "../cfg/NodeParams.cfg"
      int button_emegency_stop;
//#line 29 "../cfg/NodeParams.cfg"
      int button_hand_control_enable;
//#line 30 "../cfg/NodeParams.cfg"
      int button_hand_control_disable;
//#line 138 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;
      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("NodeConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      __toMessage__(msg, __param_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const NodeConfig &__max__ = __getMax__();
      const NodeConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const NodeConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const NodeConfig &__getDefault__();
    static const NodeConfig &__getMax__();
    static const NodeConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    
  private:
    static const NodeConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void NodeConfig::ParamDescription<std::string>::clamp(NodeConfig &config, const NodeConfig &max, const NodeConfig &min) const
  {
    return;
  }

  class NodeConfigStatics
  {
    friend class NodeConfig;
    
    NodeConfigStatics()
    {
//#line 14 "../cfg/NodeParams.cfg"
      __min__.server_hosts = "";
//#line 14 "../cfg/NodeParams.cfg"
      __max__.server_hosts = "";
//#line 14 "../cfg/NodeParams.cfg"
      __default__.server_hosts = "";
//#line 14 "../cfg/NodeParams.cfg"
      __param_descriptions__.push_back(NodeConfig::AbstractParamDescriptionConstPtr(new NodeConfig::ParamDescription<std::string>("server_hosts", "str", 0, "comma separated search list of hostnames for server", "", &NodeConfig::server_hosts)));
//#line 15 "../cfg/NodeParams.cfg"
      __min__.server_port = -2147483648;
//#line 15 "../cfg/NodeParams.cfg"
      __max__.server_port = 2147483647;
//#line 15 "../cfg/NodeParams.cfg"
      __default__.server_port = 8080;
//#line 15 "../cfg/NodeParams.cfg"
      __param_descriptions__.push_back(NodeConfig::AbstractParamDescriptionConstPtr(new NodeConfig::ParamDescription<int>("server_port", "int", 0, "ip port of server", "", &NodeConfig::server_port)));
//#line 16 "../cfg/NodeParams.cfg"
      __min__.frequency = -2147483648;
//#line 16 "../cfg/NodeParams.cfg"
      __max__.frequency = 2147483647;
//#line 16 "../cfg/NodeParams.cfg"
      __default__.frequency = 1;
//#line 16 "../cfg/NodeParams.cfg"
      __param_descriptions__.push_back(NodeConfig::AbstractParamDescriptionConstPtr(new NodeConfig::ParamDescription<int>("frequency", "int", 0, "how often to send data to server", "", &NodeConfig::frequency)));
//#line 17 "../cfg/NodeParams.cfg"
      __min__.joy_gate = -std::numeric_limits<double>::infinity();
//#line 17 "../cfg/NodeParams.cfg"
      __max__.joy_gate = std::numeric_limits<double>::infinity();
//#line 17 "../cfg/NodeParams.cfg"
      __default__.joy_gate = 1.0;
//#line 17 "../cfg/NodeParams.cfg"
      __param_descriptions__.push_back(NodeConfig::AbstractParamDescriptionConstPtr(new NodeConfig::ParamDescription<double>("joy_gate", "double", 0, "min raw joystick value to be considered != 0", "", &NodeConfig::joy_gate)));
//#line 18 "../cfg/NodeParams.cfg"
      __min__.scale_linear = -std::numeric_limits<double>::infinity();
//#line 18 "../cfg/NodeParams.cfg"
      __max__.scale_linear = std::numeric_limits<double>::infinity();
//#line 18 "../cfg/NodeParams.cfg"
      __default__.scale_linear = 1.0;
//#line 18 "../cfg/NodeParams.cfg"
      __param_descriptions__.push_back(NodeConfig::AbstractParamDescriptionConstPtr(new NodeConfig::ParamDescription<double>("scale_linear", "double", 0, "scale factor for linear speed", "", &NodeConfig::scale_linear)));
//#line 19 "../cfg/NodeParams.cfg"
      __min__.scale_angular = -std::numeric_limits<double>::infinity();
//#line 19 "../cfg/NodeParams.cfg"
      __max__.scale_angular = std::numeric_limits<double>::infinity();
//#line 19 "../cfg/NodeParams.cfg"
      __default__.scale_angular = 1.0;
//#line 19 "../cfg/NodeParams.cfg"
      __param_descriptions__.push_back(NodeConfig::AbstractParamDescriptionConstPtr(new NodeConfig::ParamDescription<double>("scale_angular", "double", 0, "scale factor for angular speed", "", &NodeConfig::scale_angular)));
//#line 20 "../cfg/NodeParams.cfg"
      __min__.scale_depth = -std::numeric_limits<double>::infinity();
//#line 20 "../cfg/NodeParams.cfg"
      __max__.scale_depth = std::numeric_limits<double>::infinity();
//#line 20 "../cfg/NodeParams.cfg"
      __default__.scale_depth = 1.0;
//#line 20 "../cfg/NodeParams.cfg"
      __param_descriptions__.push_back(NodeConfig::AbstractParamDescriptionConstPtr(new NodeConfig::ParamDescription<double>("scale_depth", "double", 0, "scale factor for depth speed", "", &NodeConfig::scale_depth)));
//#line 21 "../cfg/NodeParams.cfg"
      __min__.axis_linear = -2147483648;
//#line 21 "../cfg/NodeParams.cfg"
      __max__.axis_linear = 2147483647;
//#line 21 "../cfg/NodeParams.cfg"
      __default__.axis_linear = 1;
//#line 21 "../cfg/NodeParams.cfg"
      __param_descriptions__.push_back(NodeConfig::AbstractParamDescriptionConstPtr(new NodeConfig::ParamDescription<int>("axis_linear", "int", 0, "js axis for linear speed", "", &NodeConfig::axis_linear)));
//#line 22 "../cfg/NodeParams.cfg"
      __min__.axis_angular = -2147483648;
//#line 22 "../cfg/NodeParams.cfg"
      __max__.axis_angular = 2147483647;
//#line 22 "../cfg/NodeParams.cfg"
      __default__.axis_angular = 1;
//#line 22 "../cfg/NodeParams.cfg"
      __param_descriptions__.push_back(NodeConfig::AbstractParamDescriptionConstPtr(new NodeConfig::ParamDescription<int>("axis_angular", "int", 0, "js axis for angular speed", "", &NodeConfig::axis_angular)));
//#line 23 "../cfg/NodeParams.cfg"
      __min__.axis_depth = -2147483648;
//#line 23 "../cfg/NodeParams.cfg"
      __max__.axis_depth = 2147483647;
//#line 23 "../cfg/NodeParams.cfg"
      __default__.axis_depth = 1;
//#line 23 "../cfg/NodeParams.cfg"
      __param_descriptions__.push_back(NodeConfig::AbstractParamDescriptionConstPtr(new NodeConfig::ParamDescription<int>("axis_depth", "int", 0, "js axis for depth speed", "", &NodeConfig::axis_depth)));
//#line 24 "../cfg/NodeParams.cfg"
      __min__.use_throttle = 0;
//#line 24 "../cfg/NodeParams.cfg"
      __max__.use_throttle = 1;
//#line 24 "../cfg/NodeParams.cfg"
      __default__.use_throttle = 0;
//#line 24 "../cfg/NodeParams.cfg"
      __param_descriptions__.push_back(NodeConfig::AbstractParamDescriptionConstPtr(new NodeConfig::ParamDescription<bool>("use_throttle", "bool", 0, "use throttle instead of up/down buttons", "", &NodeConfig::use_throttle)));
//#line 25 "../cfg/NodeParams.cfg"
      __min__.depth_delta = -2147483648;
//#line 25 "../cfg/NodeParams.cfg"
      __max__.depth_delta = 2147483647;
//#line 25 "../cfg/NodeParams.cfg"
      __default__.depth_delta = 1;
//#line 25 "../cfg/NodeParams.cfg"
      __param_descriptions__.push_back(NodeConfig::AbstractParamDescriptionConstPtr(new NodeConfig::ParamDescription<int>("depth_delta", "int", 0, "how to go up/down in each step", "", &NodeConfig::depth_delta)));
//#line 26 "../cfg/NodeParams.cfg"
      __min__.button_down = -2147483648;
//#line 26 "../cfg/NodeParams.cfg"
      __max__.button_down = 2147483647;
//#line 26 "../cfg/NodeParams.cfg"
      __default__.button_down = 1;
//#line 26 "../cfg/NodeParams.cfg"
      __param_descriptions__.push_back(NodeConfig::AbstractParamDescriptionConstPtr(new NodeConfig::ParamDescription<int>("button_down", "int", 0, "button to go down", "", &NodeConfig::button_down)));
//#line 27 "../cfg/NodeParams.cfg"
      __min__.button_up = -2147483648;
//#line 27 "../cfg/NodeParams.cfg"
      __max__.button_up = 2147483647;
//#line 27 "../cfg/NodeParams.cfg"
      __default__.button_up = 1;
//#line 27 "../cfg/NodeParams.cfg"
      __param_descriptions__.push_back(NodeConfig::AbstractParamDescriptionConstPtr(new NodeConfig::ParamDescription<int>("button_up", "int", 0, "button to go up", "", &NodeConfig::button_up)));
//#line 28 "../cfg/NodeParams.cfg"
      __min__.button_emegency_stop = -2147483648;
//#line 28 "../cfg/NodeParams.cfg"
      __max__.button_emegency_stop = 2147483647;
//#line 28 "../cfg/NodeParams.cfg"
      __default__.button_emegency_stop = 1;
//#line 28 "../cfg/NodeParams.cfg"
      __param_descriptions__.push_back(NodeConfig::AbstractParamDescriptionConstPtr(new NodeConfig::ParamDescription<int>("button_emegency_stop", "int", 0, "js button for emergency stop", "", &NodeConfig::button_emegency_stop)));
//#line 29 "../cfg/NodeParams.cfg"
      __min__.button_hand_control_enable = -2147483648;
//#line 29 "../cfg/NodeParams.cfg"
      __max__.button_hand_control_enable = 2147483647;
//#line 29 "../cfg/NodeParams.cfg"
      __default__.button_hand_control_enable = 1;
//#line 29 "../cfg/NodeParams.cfg"
      __param_descriptions__.push_back(NodeConfig::AbstractParamDescriptionConstPtr(new NodeConfig::ParamDescription<int>("button_hand_control_enable", "int", 0, "js button to enable hand control", "", &NodeConfig::button_hand_control_enable)));
//#line 30 "../cfg/NodeParams.cfg"
      __min__.button_hand_control_disable = -2147483648;
//#line 30 "../cfg/NodeParams.cfg"
      __max__.button_hand_control_disable = 2147483647;
//#line 30 "../cfg/NodeParams.cfg"
      __default__.button_hand_control_disable = 1;
//#line 30 "../cfg/NodeParams.cfg"
      __param_descriptions__.push_back(NodeConfig::AbstractParamDescriptionConstPtr(new NodeConfig::ParamDescription<int>("button_hand_control_disable", "int", 0, "js button to disable hand control", "", &NodeConfig::button_hand_control_disable)));
//#line 239 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<NodeConfig::AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        __description_message__.parameters.push_back(**i);
      __max__.__toMessage__(__description_message__.max, __param_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__); 
    }
    std::vector<NodeConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    NodeConfig __max__;
    NodeConfig __min__;
    NodeConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;
    static const NodeConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static NodeConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &NodeConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const NodeConfig &NodeConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const NodeConfig &NodeConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const NodeConfig &NodeConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<NodeConfig::AbstractParamDescriptionConstPtr> &NodeConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const NodeConfigStatics *NodeConfig::__get_statics__()
  {
    const static NodeConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = NodeConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __NODERECONFIGURATOR_H__
