/* Auto-generated by genmsg_cpp for file /home/hanse/ros/ROS/hanse_ros/hanse_srvs/srv/Bool.srv */
#ifndef HANSE_SRVS_SERVICE_BOOL_H
#define HANSE_SRVS_SERVICE_BOOL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace hanse_srvs
{
template <class ContainerAllocator>
struct BoolRequest_ {
  typedef BoolRequest_<ContainerAllocator> Type;

  BoolRequest_()
  : enable(false)
  {
  }

  BoolRequest_(const ContainerAllocator& _alloc)
  : enable(false)
  {
  }

  typedef uint8_t _enable_type;
  uint8_t enable;


  typedef boost::shared_ptr< ::hanse_srvs::BoolRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hanse_srvs::BoolRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BoolRequest
typedef  ::hanse_srvs::BoolRequest_<std::allocator<void> > BoolRequest;

typedef boost::shared_ptr< ::hanse_srvs::BoolRequest> BoolRequestPtr;
typedef boost::shared_ptr< ::hanse_srvs::BoolRequest const> BoolRequestConstPtr;


template <class ContainerAllocator>
struct BoolResponse_ {
  typedef BoolResponse_<ContainerAllocator> Type;

  BoolResponse_()
  {
  }

  BoolResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::hanse_srvs::BoolResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hanse_srvs::BoolResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BoolResponse
typedef  ::hanse_srvs::BoolResponse_<std::allocator<void> > BoolResponse;

typedef boost::shared_ptr< ::hanse_srvs::BoolResponse> BoolResponsePtr;
typedef boost::shared_ptr< ::hanse_srvs::BoolResponse const> BoolResponseConstPtr;

struct Bool
{

typedef BoolRequest Request;
typedef BoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Bool
} // namespace hanse_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hanse_srvs::BoolRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hanse_srvs::BoolRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hanse_srvs::BoolRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8c1211af706069c994c06e00eb59ac9e";
  }

  static const char* value(const  ::hanse_srvs::BoolRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x8c1211af706069c9ULL;
  static const uint64_t static_value2 = 0x94c06e00eb59ac9eULL;
};

template<class ContainerAllocator>
struct DataType< ::hanse_srvs::BoolRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hanse_srvs/BoolRequest";
  }

  static const char* value(const  ::hanse_srvs::BoolRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hanse_srvs::BoolRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool enable\n\
\n\
";
  }

  static const char* value(const  ::hanse_srvs::BoolRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::hanse_srvs::BoolRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hanse_srvs::BoolResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hanse_srvs::BoolResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hanse_srvs::BoolResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::hanse_srvs::BoolResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::hanse_srvs::BoolResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hanse_srvs/BoolResponse";
  }

  static const char* value(const  ::hanse_srvs::BoolResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hanse_srvs::BoolResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::hanse_srvs::BoolResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::hanse_srvs::BoolResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hanse_srvs::BoolRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.enable);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BoolRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hanse_srvs::BoolResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BoolResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<hanse_srvs::Bool> {
  static const char* value() 
  {
    return "8c1211af706069c994c06e00eb59ac9e";
  }

  static const char* value(const hanse_srvs::Bool&) { return value(); } 
};

template<>
struct DataType<hanse_srvs::Bool> {
  static const char* value() 
  {
    return "hanse_srvs/Bool";
  }

  static const char* value(const hanse_srvs::Bool&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<hanse_srvs::BoolRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8c1211af706069c994c06e00eb59ac9e";
  }

  static const char* value(const hanse_srvs::BoolRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<hanse_srvs::BoolRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hanse_srvs/Bool";
  }

  static const char* value(const hanse_srvs::BoolRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<hanse_srvs::BoolResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8c1211af706069c994c06e00eb59ac9e";
  }

  static const char* value(const hanse_srvs::BoolResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<hanse_srvs::BoolResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hanse_srvs/Bool";
  }

  static const char* value(const hanse_srvs::BoolResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // HANSE_SRVS_SERVICE_BOOL_H

