/* Auto-generated by genmsg_cpp for file /home/hanse/ros/ROS/hanse_ros/hanse_srvs/srv/Empty.srv */
#ifndef HANSE_SRVS_SERVICE_EMPTY_H
#define HANSE_SRVS_SERVICE_EMPTY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace hanse_srvs
{
template <class ContainerAllocator>
struct EmptyRequest_ {
  typedef EmptyRequest_<ContainerAllocator> Type;

  EmptyRequest_()
  {
  }

  EmptyRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::hanse_srvs::EmptyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hanse_srvs::EmptyRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct EmptyRequest
typedef  ::hanse_srvs::EmptyRequest_<std::allocator<void> > EmptyRequest;

typedef boost::shared_ptr< ::hanse_srvs::EmptyRequest> EmptyRequestPtr;
typedef boost::shared_ptr< ::hanse_srvs::EmptyRequest const> EmptyRequestConstPtr;


template <class ContainerAllocator>
struct EmptyResponse_ {
  typedef EmptyResponse_<ContainerAllocator> Type;

  EmptyResponse_()
  {
  }

  EmptyResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::hanse_srvs::EmptyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hanse_srvs::EmptyResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct EmptyResponse
typedef  ::hanse_srvs::EmptyResponse_<std::allocator<void> > EmptyResponse;

typedef boost::shared_ptr< ::hanse_srvs::EmptyResponse> EmptyResponsePtr;
typedef boost::shared_ptr< ::hanse_srvs::EmptyResponse const> EmptyResponseConstPtr;

struct Empty
{

typedef EmptyRequest Request;
typedef EmptyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct Empty
} // namespace hanse_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hanse_srvs::EmptyRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hanse_srvs::EmptyRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hanse_srvs::EmptyRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::hanse_srvs::EmptyRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::hanse_srvs::EmptyRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hanse_srvs/EmptyRequest";
  }

  static const char* value(const  ::hanse_srvs::EmptyRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hanse_srvs::EmptyRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::hanse_srvs::EmptyRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::hanse_srvs::EmptyRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hanse_srvs::EmptyResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hanse_srvs::EmptyResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hanse_srvs::EmptyResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::hanse_srvs::EmptyResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::hanse_srvs::EmptyResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hanse_srvs/EmptyResponse";
  }

  static const char* value(const  ::hanse_srvs::EmptyResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hanse_srvs::EmptyResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::hanse_srvs::EmptyResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::hanse_srvs::EmptyResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hanse_srvs::EmptyRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct EmptyRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hanse_srvs::EmptyResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct EmptyResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<hanse_srvs::Empty> {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const hanse_srvs::Empty&) { return value(); } 
};

template<>
struct DataType<hanse_srvs::Empty> {
  static const char* value() 
  {
    return "hanse_srvs/Empty";
  }

  static const char* value(const hanse_srvs::Empty&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<hanse_srvs::EmptyRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const hanse_srvs::EmptyRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<hanse_srvs::EmptyRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hanse_srvs/Empty";
  }

  static const char* value(const hanse_srvs::EmptyRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<hanse_srvs::EmptyResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const hanse_srvs::EmptyResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<hanse_srvs::EmptyResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hanse_srvs/Empty";
  }

  static const char* value(const hanse_srvs::EmptyResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // HANSE_SRVS_SERVICE_EMPTY_H

