/* Auto-generated by genmsg_cpp for file /home/hanse/ros/ROS/hanse_ros/hanse_srvs/srv/GetOutput.srv */
#ifndef HANSE_SRVS_SERVICE_GETOUTPUT_H
#define HANSE_SRVS_SERVICE_GETOUTPUT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace hanse_srvs
{
template <class ContainerAllocator>
struct GetOutputRequest_ {
  typedef GetOutputRequest_<ContainerAllocator> Type;

  GetOutputRequest_()
  {
  }

  GetOutputRequest_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::hanse_srvs::GetOutputRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hanse_srvs::GetOutputRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetOutputRequest
typedef  ::hanse_srvs::GetOutputRequest_<std::allocator<void> > GetOutputRequest;

typedef boost::shared_ptr< ::hanse_srvs::GetOutputRequest> GetOutputRequestPtr;
typedef boost::shared_ptr< ::hanse_srvs::GetOutputRequest const> GetOutputRequestConstPtr;


template <class ContainerAllocator>
struct GetOutputResponse_ {
  typedef GetOutputResponse_<ContainerAllocator> Type;

  GetOutputResponse_()
  : output(0.0)
  {
  }

  GetOutputResponse_(const ContainerAllocator& _alloc)
  : output(0.0)
  {
  }

  typedef double _output_type;
  double output;


  typedef boost::shared_ptr< ::hanse_srvs::GetOutputResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hanse_srvs::GetOutputResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct GetOutputResponse
typedef  ::hanse_srvs::GetOutputResponse_<std::allocator<void> > GetOutputResponse;

typedef boost::shared_ptr< ::hanse_srvs::GetOutputResponse> GetOutputResponsePtr;
typedef boost::shared_ptr< ::hanse_srvs::GetOutputResponse const> GetOutputResponseConstPtr;

struct GetOutput
{

typedef GetOutputRequest Request;
typedef GetOutputResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GetOutput
} // namespace hanse_srvs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hanse_srvs::GetOutputRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hanse_srvs::GetOutputRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hanse_srvs::GetOutputRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::hanse_srvs::GetOutputRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::hanse_srvs::GetOutputRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hanse_srvs/GetOutputRequest";
  }

  static const char* value(const  ::hanse_srvs::GetOutputRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hanse_srvs::GetOutputRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::hanse_srvs::GetOutputRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::hanse_srvs::GetOutputRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hanse_srvs::GetOutputResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hanse_srvs::GetOutputResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hanse_srvs::GetOutputResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5dd87a43ba76105996c6c8cafb738498";
  }

  static const char* value(const  ::hanse_srvs::GetOutputResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5dd87a43ba761059ULL;
  static const uint64_t static_value2 = 0x96c6c8cafb738498ULL;
};

template<class ContainerAllocator>
struct DataType< ::hanse_srvs::GetOutputResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hanse_srvs/GetOutputResponse";
  }

  static const char* value(const  ::hanse_srvs::GetOutputResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hanse_srvs::GetOutputResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 output\n\
\n\
\n\
";
  }

  static const char* value(const  ::hanse_srvs::GetOutputResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::hanse_srvs::GetOutputResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hanse_srvs::GetOutputRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetOutputRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hanse_srvs::GetOutputResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.output);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetOutputResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<hanse_srvs::GetOutput> {
  static const char* value() 
  {
    return "5dd87a43ba76105996c6c8cafb738498";
  }

  static const char* value(const hanse_srvs::GetOutput&) { return value(); } 
};

template<>
struct DataType<hanse_srvs::GetOutput> {
  static const char* value() 
  {
    return "hanse_srvs/GetOutput";
  }

  static const char* value(const hanse_srvs::GetOutput&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<hanse_srvs::GetOutputRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5dd87a43ba76105996c6c8cafb738498";
  }

  static const char* value(const hanse_srvs::GetOutputRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<hanse_srvs::GetOutputRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hanse_srvs/GetOutput";
  }

  static const char* value(const hanse_srvs::GetOutputRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<hanse_srvs::GetOutputResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5dd87a43ba76105996c6c8cafb738498";
  }

  static const char* value(const hanse_srvs::GetOutputResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<hanse_srvs::GetOutputResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hanse_srvs/GetOutput";
  }

  static const char* value(const hanse_srvs::GetOutputResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // HANSE_SRVS_SERVICE_GETOUTPUT_H

