# A=0, B=1, X=2, Y=3, LB = 4, LR = 5, BACK=6, START=7, CENTER=8, DPAD_L=11, DPAD_R=12, DPAD_UP=13, DPAD_DOWN=14

{
publish_frequency: 10,
gamepad_switch_button: 0,
joy_deadzone: 0.15,
linear_axis: 1,
linear_scale: 1.0,
angular_axis: 3,
angular_scale: 1.0, # 10 fuer PID
depth_up_button: 13,
depth_down_button: 14,
depth_delta: 10,
zero_depth_reset_button: 1,
motor_switch_button: 8,
pid_switch_button: 6,
emergency_stop_button: 7
}
